name: Build android package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt install -y make openjdk-8-jdk openjdk-8-jre ant-contrib python3-requests python3-pip
        sudo pip3 install websocket-client
        git clone --depth 1 https://gitlab.com/LostGamer/ndk-binaries
        git clone --depth 1 https://gitlab.com/LostGamer/android-sdk
        DEPLOY_BRANCH=srceng-old-port COMMIT=$(git rev-parse HEAD) scripts/workflow.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: compiled-debug
          path: bin/srceng-debug.apk
